version: '3.8'

services:
  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    command: npm run start

  redis:
    image: bitnami/redis:latest
    container_name: pokemon-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - data_redis:/bitnami/redis/data

volumes:
  data_redis:
